### ISSUE TITLE
Could not load JIntellitype.dll from local file system or from inside JAR

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melloware/jintellitype#13]
```
What steps will reproduce the problem?
1. Add JAR to Netbeans project
2. Make sure DLL is in project folder
3. Run through Netbeans IDE

What is the expected output? What do you see instead?
Expected:  Running with hotkey support

Instead: 

Exception in thread "AWT-EventQueue-0" 
com.melloware.jintellitype.JIntellitypeException: Could not load 
JIntellitype.dll from local file system or from inside JAR
    at com.melloware.jintellitype.JIntellitype.<init>(JIntellitype.java:114)
    at com.melloware.jintellitype.JIntellitype.getInstance(JIntellitype.java:177)
    at marketbot.SettingsWindow.<init>(SettingsWindow.java:32)
    at marketbot.MarketBot$2.run(MarketBot.java:129)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.io.IOException: FromJarToFileSystem could not load DLL: 
com/melloware/jintellitype/JIntellitype.dll
    at com.melloware.jintellitype.JIntellitype.fromJarToFs(JIntellitype.java:150)
    at com.melloware.jintellitype.JIntellitype.<init>(JIntellitype.java:105)
    ... 17 more
Caused by: java.lang.NullPointerException
    at com.melloware.jintellitype.JIntellitype.fromJarToFs(JIntellitype.java:146)
    ... 18 more

What version of the product are you using? On what operating system?

I'm using v1.3.9 on Windows 8.1.


Please provide any additional information below.

The following code is what I am using:

File f = new 
File("C:\\Users\\Christopher\\Documents\\NetBeansProjects\\MarketBot\\jintellity
pe-1.3.9\\JIntellitype.dll");
        if (f.exists())
            System.out.println("Library exists!");
        JIntellitype.setLibraryLocation(f);
        initComponents();
        JIntellitype.getInstance();
        JIntellitype.getInstance().registerHotKey(1, JIntellitype.MOD_CONTROL, (int)'0');


It worked all day yesterday, but after a computer reboot, it has stopped.  I 
have no idea what a reboot could have changed...

Also related: 
http://stackoverflow.com/questions/24481260/problems-adding-native-dlls-to-java-
runtime-jintellitype
```

Original issue reported on code.google.com by `chriskin...@gmail.com` on 30 Jun 2014 at 12:07

**Comment by caelumable** [comment]
> 
> 
> ```
> Well, I'm not entirely sure why, but I decided to install Java x64, switch my 
> environment to 64-bit and use the 64 bit DLL and it now works perfectly.  I 
> guess ~magic~ happened  :? 
> 
> 
> ^ Just for anyone else who has problems
> ```
> 
> Original comment by `chriskin...@gmail.com` on 30 Jun 2014 at 9:25

yeah,it's a magic. I also solved my problem, I renamed the JIntellitype64.dll to JIntellitype.dll and put it into the system32 folder and put it into the project folder then the magic happend.

**Comment by melloware** [comment]
Nice thanks for posting @caelumable
