### ISSUE TITLE
NullPointerException in "JIntellitypeDemo.java"

### ISSUE THREAD

**Issue by ghost** [melloware/jintellitype#28]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.melloware.jintellitype.JIntellitypeDemo.main(JIntellitypeDemo.java:86)
Caused by: com.melloware.jintellitype.JIntellitypeException: Could not load JIntellitype.dll from local file system or from inside JAR
	at com.melloware.jintellitype.JIntellitype.loadLibrary(JIntellitype.java:143)
	at com.melloware.jintellitype.JIntellitype.<clinit>(JIntellitype.java:63)
	... 1 more
Caused by: java.io.IOException: FromJarToFileSystem could not load DLL: com/melloware/jintellitype/windows/JIntellitype64.dll
	at com.melloware.jintellitype.JIntellitype.fromJarToFs(JIntellitype.java:181)
	at com.melloware.jintellitype.JIntellitype.loadLibrary(JIntellitype.java:140)
	... 2 more
Caused by: java.lang.NullPointerException
	at com.melloware.jintellitype.JIntellitype.fromJarToFs(JIntellitype.java:177)
	... 3 more

**Comment by melloware** [comment]
Make sure you have JINtellitype.dll or Jintelltiype64.dll in the C:\Windows\System folder.
